import os
import json
import requests
from bs4 import BeautifulSoup
import openai

# Note: This is an automation script to massively expand the competitor SEO net.
# Run this script on a weekly cron job. It searches Google/Product Hunt for new
# "AI PDF" tools, and automatically writes the JSON required to spin up a new
# `/compare/paperlens-vs-[new-competitor]` landing page.

openai.api_key = os.getenv("OPENAI_API_KEY")

def search_new_competitors():
    # In a real production script, you would use SERP API or Google Custom Search API
    # Here we mock the behavior of finding a trending new tool on Product Hunt
    print("Searching for trending AI PDF tools...")
    return ["PDF.ai", "Coral AI", "Docubaat"]

def generate_competitor_comparison(competitor_name):
    prompt = f"""
    You are an expert SEO copywriter. We are building a comparison landing page for "PaperLens AI vs {competitor_name}".
    Write a JSON object strictly following this format:
    {{
        "slug": "paperlens-vs-{competitor_name.lower().replace('.', '').replace(' ', '-')}",
        "competitorName": "{competitor_name}",
        "title": "PaperLens vs {competitor_name} | Best AI PDF Analyzer 2026",
        "description": "See why PaperLens is the best alternative to {competitor_name} for analyzing long PDFs, verifying citations, and extracting data.",
        "heading": "PaperLens vs {competitor_name}",
        "subheading": "A detailed comparison. Discover why professionals choose PaperLens for secure, hallucination-free document analysis.",
        "pros": ["PaperLens has strict citation verification", "PaperLens allows 50 documents at once"],
        "cons": ["{competitor_name} often hallucinates facts", "{competitor_name} struggles with 100+ page documents"]
    }}
    Output ONLY valid JSON.
    """
    
    response = openai.chat.completions.create(
        model="gpt-4-turbo",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
        response_format={ "type": "json_object" }
    )
    
    return json.loads(response.choices[0].message.content)

if __name__ == "__main__":
    competitors = search_new_competitors()
    registry = {}
    
    print("Generating SEO Comparison Matrix...")
    for comp in competitors:
        print(f"Generating page for: {comp}")
        data = generate_competitor_comparison(comp)
        registry[data['slug']] = data
        
    ts_output = f"""
// AUTO-GENERATED BY scripts/competitor_monitor.py
export const DYNAMIC_COMPARISONS_REGISTRY = {json.dumps(registry, indent=2)};
"""
    
    with open("dynamic_comparisons.ts", "w") as f:
        f.write(ts_output)
    
    print("Successfully generated dynamic_comparisons.ts! Append this to src/data/comparisons.ts to deploy new landing pages automatically.")
