import os
import json
import openai

# Note: This is an automation script to massively expand the SEO engine.
# Run this script locally with your OPENAI_API_KEY to generate hundreds of glossary terms.
# It outputs a TypeScript file that you can directly paste into src/data/glossary.ts

openai.api_key = os.getenv("OPENAI_API_KEY")

TERMS_TO_GENERATE = [
    "Force Majeure",
    "Net 30 Terms",
    "Null Hypothesis",
    "Capital Expenditure",
    "Non-Compete Clause"
]

def generate_seo_glossary(term):
    prompt = f"""
    You are an expert SEO copywriter and legal/financial/academic analyst.
    Write a JSON object for a glossary term page for the concept "{term}".
    The object must strictly follow this format:
    {{
        "slug": "url-friendly-slug",
        "term": "The Term",
        "category": "Legal" | "Financial" | "Academic" | "General",
        "shortDefinition": "A 1-sentence definition.",
        "detailedExplanation": "A 3-4 sentence detailed explanation of what this is.",
        "howPaperLensHelps": "A 2-3 sentence explanation of how an AI tool called PaperLens (which analyzes PDFs, extracts clauses, and verifies citations) can help a user find, analyze, or summarize this term in a large document."
    }}
    Output ONLY valid JSON.
    """
    
    response = openai.chat.completions.create(
        model="gpt-4-turbo",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
        response_format={ "type": "json_object" }
    )
    
    return json.loads(response.choices[0].message.content)

if __name__ == "__main__":
    registry = {}
    print("Generating SEO Glossary Matrix...")
    
    for term in TERMS_TO_GENERATE:
        print(f"Generating for: {term}")
        data = generate_seo_glossary(term)
        registry[data['slug']] = data
        
    ts_output = f"""
// AUTO-GENERATED BY scripts/generate_glossary.py
export const GLOSSARY_REGISTRY = {json.dumps(registry, indent=2)};
export const allGlossaryTermsList = Object.values(GLOSSARY_REGISTRY);
"""
    
    with open("glossary_generated.ts", "w") as f:
        f.write(ts_output)
    
    print("Successfully generated glossary_generated.ts!")
